name: multi_tools_app
description: A Flutter application with multiple utility tools.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  torch_light: ^1.0.0
  sensors_plus: ^3.0.3
  intl: ^0.19.0
  http: ^1.1.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  change_app_package_name: ^1.5.0
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/sounds/dice_roll.mp3

